### ISSUE TITLE
Cannot require dependencies from the default location of .hyper-postprocessing.js

### ISSUE THREAD

**Issue by marcofugaro** [slammayjammay/hyper-postprocessing#16]
Hi! Great plugin!

I followed the installation steps and created the config file in the home like `~/.hyper-postprocessing.js`.

However when I restarted hyper I was greeted with this error:

![image](https://user-images.githubusercontent.com/7217420/56291390-7c621e00-6125-11e9-9d01-0fddbb456e3f.png)

This is because the dependencies are installed in the .hyper_plugins folder, so they're not accessible from the home folder unless you specify the path.

So I solved it like this:

```js
const THREE = require('./.hyper_plugins/node_modules/three')
const {
  EffectPass,
  Effect,
  ScanlineEffect,
} = require('./.hyper_plugins/node_modules/postprocessing')
```

The alternative is to place the `.hyper-postprocessing.js` inside the .hyper_plugins folder, that way the `require('postprocessing')` would work fine. 

What would be the most handy way in your opinion? I can make a PR and update the readme if you want

**Comment by slammayjammay** [comment]
Thanks! Ok good question this is a little tricky. For now you can keep requiring from this plugin's node_modules, or better install `three` and `postprocessing` separately as long as you keep the major version the same as the ones used here.

I think the ideal solution is to set those as peer dependencies and then install them separately from this plugin, though because of the way Hyper's plugin system works I think you'd have to jump through some hoops to make it work and ultimately might not be worth the trouble.

The plugin folder is managed by Hyper, and placing the entry file inside it could possibly cause conflicts down the road so I don't recommend that.

Let me think about it for a little bit. I'm also open to any ideas on how to solve.

**Comment by marcofugaro** [comment]
@slammayjammay I would go for the option to require them as `./.hyper_plugins/node_modules/three`, that folder structure probably won't change in the future.

I don't think it's a good idea to make the user install manually these dependencies, especially if they are global dependecies, that can cause all sorts of issues in the long run

**Comment by slammayjammay** [comment]
I agree they shouldn't be installed as global dependencies, though I could see how it's misleading if the default entry file is inside the home folder. It makes more sense for users to create a directory to house anything related to this plugin and install dependencies there.

I think there should be an option to allow users to install and require those as peer dependencies, but not force it on them. If they do install those packages then this plugin can use them, if not then it will use a default version. That way any non-breaking changes to those packages can be absorbed without needing to rerelease this plugin and it will still work out of the box.

**Comment by slammayjammay** [comment]
Added a note about it in the readme https://github.com/slammayjammay/hyper-postprocessing#a-note-about-dependencies

**Comment by norill** [comment]
you could place entry module in `.hyper_plugins/local` - that way `require('postprocessing')` would use module from `../node_modules/postprocessing` i.e `hyper_plugins/node_modules/postprocessing`
