### ISSUE TITLE
BloomEffect stopped working

### ISSUE THREAD

**Issue by changbowen** [slammayjammay/hyper-postprocessing#23]
I think the BloomEffect has stopped working since the v6.6.0 release of Post Processing.
I saw lots of properties of BloomEffect got deprecated [in that release ](https://github.com/vanruesc/postprocessing/releases/tag/v6.6.0)and perhaps that's why.
Still works after manually replacing with v6.5.1.

**Comment by vanruesc** [comment]
This might have to do with the `distinction` factor.

The `distinction` constructor parameter of the `BloomEffect` was replaced by `luminanceThreshold` and `luminanceSmoothing` and the `distinction` field was replaced by `luminanceMaterial.threshold` and `luminanceMaterial.smoothing`.

The default threshold is `0.9` so only very bright colors will bloom if left untouched.

I guess this was a somewhat breaking change after all. Oh well 😅

**Comment by changbowen** [comment]
Haven't worked much with Node but I'm guessing a quick fix would be changing the dependency to limit the version of postprocessing and perhaps three (according to the v6.5.1 release):
```
"dependencies": {
  "postprocessing": ">= 6.2.1 < 6.6.0",
  "three": ">= 0.103.0 < 0.107.0"
}
```
😉

**Comment by changbowen** [comment]
A separate question, how can I apply a transform to a pass that zooms out the canvas a bit?
Appreciate your help :)

**Comment by vanruesc** [comment]
Does changing the threshold fix the problem with the `BloomEffect`? It'd be great if you could test that out.

> how can I apply a transform to a pass that zooms out the canvas a bit?

You can use a custom pass to scale the frame buffer, but I'm not sure if that's what you're trying to do:
https://codesandbox.io/s/postprocessing-scale-rkgtq

**Comment by changbowen** [comment]
Indeed with v6.7.0 setting luminanceThreshold and luminanceSmoothing both to 0 gives a subtle bloom. It is less intense than the old bloom effect could get to (by setting distinction to negative values). But gives more control over the style. Good enough for me :)

There is actually a scale.glsl and I used it like this: 
```
const scaleEffect = new GlslEffect('scale', {
	defines: new Map([['scale', '0.99']])
})
```
It works fine mostly. Only on the edges there is this weird "artifact":
![image](https://user-images.githubusercontent.com/15975872/65672275-526d3a00-e07b-11e9-8223-d3a0ac750b04.png)
Looked the same as in your link. Any ways to avoid that?

**Comment by vanruesc** [comment]
> It is less intense than the old bloom effect could get to (by setting distinction to negative values).

If you don't need to filter bright colors and want to bloom everything except black, you should consider disabling the luminance filter to improve performance. The intensity of the `BloomEffect` can be controlled via its opacity:

```js
bloomEffect.luminancePass.enabled = false;
bloomEffect.blendMode.opacity.value = 2.3; // Default is 1.
```

> It works fine mostly. Only on the edges there is this weird "artifact"
> Any ways to avoid that?

If the background color is black and there's at least one pixel between the screen edge and your text, it should be possible to fix this by first scaling your terminal and then applying bloom to the scaled image. In the screenshot you provided, it looks like you first apply bloom and then scale the result down.

I tried to replicate this here: https://codesandbox.io/s/postprocessing-scale-9z44c
If anything touches the screen edge, it will smear because of the CLAMP_TO_EDGE texture wrap mode. Unfortunately, WebGL (and OpenGL ES) doesn't support CLAMP_TO_BORDER.

> A final smaaEffect pass fixes the edge but also further blurs the texts

Try to move more of your effects into the `EffectPass` that has the `SMAAEffect` in it. That way the antialiasing might end up looking better. SMAA usually doesn't introduce any noticeable blurring.

**Comment by slammayjammay** [comment]
@vanruesc thanks for taking care of this one!

@changbowen is this good to close?

**Comment by changbowen** [comment]
Yes please. Thanks for the tips!
